# Generated by Django 5.2 on 2025-05-13 07:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='last_update',
        ),
        migrations.AddField(
            model_name='stock',
            name='date_entree',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='date_sortie',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
