# Generated by Django 5.2 on 2025-05-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0002_remove_stock_last_update_stock_date_entree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_entree',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
