# Generated by Django 5.2 on 2025-05-14 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0003_alter_stock_date_entree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_entree',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
