# Generated by Django 5.2 on 2025-05-14 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0004_alter_stock_date_entree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_entree',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
