# Generated by Django 5.2 on 2025-05-15 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0005_alter_stock_date_entree'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='etat',
            field=models.CharField(default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_produit.produit'),
        ),
    ]
