# Generated by Django 5.2 on 2025-05-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0006_stock_etat_alter_stock_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='etat',
            field=models.CharField(default='rupture', max_length=20),
        ),
    ]
